services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydb'
    #      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
    #      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
