server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/mydb
#      host: localhost
#      port: 27017
#      database: mydb
#      username: root
#      password: 1234
#      authentication-database: admin
#
