server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb
      #      host: localhost
      #      port: 27017
      #      database: mydb
      #      username: root
      #      password: 1234
      test:
        connectionString: mongodb://localhost:27017/test
      authentication-database: mydb
