# https://youngwonhan-family.tistory.com/entry/Docker-mongodb-docker-compose-%EC%84%A4%EC%B9%98-%EB%B0%8F-%EB%8D%B0%EC%9D%B4%ED%84%B0-CRUD-%EC%98%88%EC%A0%9C
# https://www.mongodb.com/try/download/compass
version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    #    restart: always
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - "27017:27017"
# docker-compose -f ./docker-mongodb.yml up -d